<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket102.xml
 */
namespace sul\protocol\play\pocket102;

use utils\Packet;

class DropItem extends Packet
{

    public const ID = 46;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    // action
    public const DROP = 0;

    public $action;
    public $item;

    public function __constructor() {}

    public function __constructor($action, \sul\protocol\pocket102\types\Slot $item)
    {
        $this->action = $action;
        $this->item = $item;
    }

}

