<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket102.xml
 */
namespace sul\protocol\play\pocket102;

use utils\Packet;

class MobEquipment extends Packet
{

    public const ID = 32;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = true;

    public $entityId;
    public $item;
    public $inventorySlot;
    public $hotbarSlot;
    public $?;

    public function __constructor() {}

    public function __constructor($entityId, \sul\protocol\pocket102\types\Slot $item, $inventorySlot, $hotbarSlot, $?)
    {
        $this->entityId = $entityId;
        $this->item = $item;
        $this->inventorySlot = $inventorySlot;
        $this->hotbarSlot = $hotbarSlot;
        $this->? = $?;
    }

}

