<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
namespace sul\protocol\player\hncom2;

use utils\Packet;

class UpdateLatency extends Packet
{

    public const ID = 27;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $hubId;
    public $latency;

    public function __constructor() {}

    public function __constructor($hubId, $latency)
    {
        $this->hubId = $hubId;
        $this->latency = $latency;
    }

}

