<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket133.xml
 */
namespace sul\protocol\play\pocket133;

use utils\Packet;

class AddPainting extends Packet
{

    public const ID = 22;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $entityId;
    public $runtimeId;
    public $position;
    public $direction;
    public $title;

    public function __constructor() {}

    public function __constructor($entityId, $runtimeId, \sul\protocol\pocket133\types\BlockPosition $position, $direction, $title)
    {
        $this->entityId = $entityId;
        $this->runtimeId = $runtimeId;
        $this->position = $position;
        $this->direction = $direction;
        $this->title = $title;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {





    }

    public function decode()
    {}

}

