<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/bedrock137.xml
 */
namespace sul\protocol\play\bedrock;

use utils\Packet;

class ContainerSetData extends Packet
{

    public const ID = 51;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $window;
    public $property;
    public $value;

    public function __constructor() {}

    public function __constructor($window, $property, $value)
    {
        $this->window = $window;
        $this->property = $property;
        $this->value = $value;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {



    }

    public function decode()
    {}

}

