<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
namespace sul\protocol\player\hncom;

use utils\Packet;

class OrderedGamePacket extends Packet
{

    public const ID = 30;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $hubId;
    public $order;
    public $packet;

    public function __constructor() {}

    public function __constructor($hubId, $order, $packet)
    {
        $this->hubId = $hubId;
        $this->order = $order;
        $this->packet = $packet;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {



    }

    public function decode()
    {}

}

