<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
namespace sul\protocol\player\hncom;

use utils\Packet;

class Transfer extends Packet
{

    public const ID = 20;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    // on fail
    public const DISCONNECT = 0;
    public const AUTO = 1;
    public const RECONNECT = 2;

    public $hubId;
    public $node;
    public $onFail;

    public function __constructor() {}

    public function __constructor($hubId, $node, $onFail)
    {
        $this->hubId = $hubId;
        $this->node = $node;
        $this->onFail = $onFail;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {



    }

    public function decode()
    {}

}

