<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/externalconsole2.xml
 */
namespace sul\protocol\login\externalconsole2;

use utils\Packet;

class AuthCredentials extends Packet
{

    public const ID = 0;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $protocol;
    public $hash;
    public $hashAlgorithm;
    public $payload;

    public function __constructor() {}

    public function __constructor($protocol, $hash, $hashAlgorithm, $payload)
    {
        $this->protocol = $protocol;
        $this->hash = $hash;
        $this->hashAlgorithm = $hashAlgorithm;
        $this->payload = $payload;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {




    }

    public function decode()
    {}

}

