<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft108.xml
 */
namespace sul\protocol\clientbound\minecraft108;

use utils\Packet;

class SpawnPosition extends Packet
{

    public const ID = 67;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $position;

    public function __constructor() {}

    public function __constructor($position)
    {
        $this->position = $position;
    }

}

