<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft108.xml
 */
namespace sul\protocol\clientbound\minecraft108;

use utils\Packet;

class EntityEffect extends Packet
{

    public const ID = 76;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $entityId;
    public $effectId;
    public $amplifier;
    public $duration;
    public $hideParticles;

    public function __constructor() {}

    public function __constructor($entityId, $effectId, $amplifier, $duration, $hideParticles)
    {
        $this->entityId = $entityId;
        $this->effectId = $effectId;
        $this->amplifier = $amplifier;
        $this->duration = $duration;
        $this->hideParticles = $hideParticles;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {





    }

    public function decode()
    {}

}

