<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket112.xml
 */
namespace sul\protocol\play\pocket112;

use utils\Packet;

class MovePlayer extends Packet
{

    public const ID = 19;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = true;

    // animation
    public const FULL = 0;
    public const NONE = 1;
    public const TELEPORT = 2;
    public const PITCH = 3;

    public $entityId;
    public $position;
    public $pitch;
    public $headYaw;
    public $yaw;
    public $animation;
    public $onGround;
    public $?;
    public $?;
    public $?;

    public function __constructor() {}

    public function __constructor($entityId, $position, $pitch, $headYaw, $yaw, $animation, $onGround, $?, $?, $?)
    {
        $this->entityId = $entityId;
        $this->position = $position;
        $this->pitch = $pitch;
        $this->headYaw = $headYaw;
        $this->yaw = $yaw;
        $this->animation = $animation;
        $this->onGround = $onGround;
        $this->? = $?;
        $this->? = $?;
        $this->? = $?;
    }

}

