<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/bedrock141.xml
 */
namespace sul\protocol\play\bedrock141;

use utils\Packet;

class ServerSettingsResponse extends Packet
{

    public const ID = 103;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $formId;
    public $data;

    public function __constructor() {}

    public function __constructor($formId, $data)
    {
        $this->formId = $formId;
        $this->data = $data;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {


    }

    public function decode()
    {}

}

