<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
namespace sul\protocol\status\hncom2;

use utils\Packet;

class MessageClientbound extends Packet
{

    public const ID = 10;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $sender;
    public $payload;

    public function __constructor() {}

    public function __constructor($sender, $payload)
    {
        $this->sender = $sender;
        $this->payload = $payload;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {


    }

    public function decode()
    {}

}

