<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
namespace sul\protocol\status\hncom;

use utils\Packet;

class UpdateList extends Packet
{

    public const ID = 15;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    // list
    public const WHITELIST = 0;
    public const BLACKLIST = 1;

    // action
    public const ADD = 0;
    public const REMOVE = 1;

    public $list;
    public $action;
    public $type;

    public function __constructor() {}

    public function __constructor($list, $action, $type)
    {
        $this->list = $list;
        $this->action = $action;
        $this->type = $type;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {



    }

    public function decode()
    {}

}

