<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
namespace sul\protocol\play\pocket100;

use utils\Packet;

class Animate extends Packet
{

    public const ID = 44;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = true;

    // action
    public const BREAKING = 1;
    public const WAKE_UP = 3;

    public $action;
    public $entityId;

    public function __constructor() {}

    public function __constructor($action, $entityId)
    {
        $this->action = $action;
        $this->entityId = $entityId;
    }

}

