<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
namespace sul\protocol\play\pocket100;

use utils\Packet;

class MoveEntity extends Packet
{

    public const ID = 19;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $entityId;
    public $position;
    public $pitch;
    public $headYaw;
    public $yaw;

    public function __constructor() {}

    public function __constructor($entityId, $position, $pitch, $headYaw, $yaw)
    {
        $this->entityId = $entityId;
        $this->position = $position;
        $this->pitch = $pitch;
        $this->headYaw = $headYaw;
        $this->yaw = $yaw;
    }

}

