<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
namespace sul\protocol\play\pocket100;

use utils\Packet;

class PlayerFall extends Packet
{

    public const ID = 37;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $distance;

    public function __constructor() {}

    public function __constructor($distance)
    {
        $this->distance = $distance;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {

    }

    public function decode()
    {}

}

