<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket101.xml
 */
namespace sul\protocol\play\pocket101;

use utils\Packet;

class ContainerClose extends Packet
{

    public const ID = 49;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = true;

    public $window;

    public function __constructor() {}

    public function __constructor($window)
    {
        $this->window = $window;
    }

}

