<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket101.xml
 */
namespace sul\protocol\play\pocket101;

use utils\Packet;

class PlayerInput extends Packet
{

    public const ID = 57;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $motion;
    public $flags;
    public $?;

    public function __constructor() {}

    public function __constructor($motion, $flags, $?)
    {
        $this->motion = $motion;
        $this->flags = $flags;
        $this->? = $?;
    }

}

