<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/bedrock150.xml
 */
namespace sul\protocol\play\bedrock150;

use utils\Packet;

class NpcRequest extends Packet
{

    public const ID = 98;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $entityId;
    public $requestType;
    public $command;
    public $actionType;

    public function __constructor() {}

    public function __constructor($entityId, $requestType, $command, $actionType)
    {
        $this->entityId = $entityId;
        $this->requestType = $requestType;
        $this->command = $command;
        $this->actionType = $actionType;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {




    }

    public function decode()
    {}

}

