<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/externalconsole2.xml
 */
namespace sul\protocol\connected\externalconsole2;

use utils\Packet;

class ConsoleMessage extends Packet
{

    public const ID = 4;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $node;
    public $timestamp;
    public $logger;
    public $message;
    public $commandId;

    public function __constructor() {}

    public function __constructor($node, $timestamp, $logger, $message, $commandId)
    {
        $this->node = $node;
        $this->timestamp = $timestamp;
        $this->logger = $logger;
        $this->message = $message;
        $this->commandId = $commandId;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {





    }

    public function decode()
    {}

}

