<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket111.xml
 */
namespace sul\protocol\play\pocket111;

use utils\Packet;

class LevelEvent extends Packet
{

    public const ID = 26;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    // event id
    public const START_RAIN = 3001;
    public const START_THUNDER = 3002;
    public const STOP_RAIN = 3003;
    public const STOP_THUNDER = 3004;
    public const SET_DATA = 4000;
    public const PLAYERS_SLEEPING = 9800;
    public const BUBBLE = 16385;
    public const CRITICAL = 16386;
    public const BLOCK_FORCE_FIELD = 16387;
    public const SMOKE = 16388;
    public const EXPLODE = 16389;
    public const EVAPORATION = 16390;
    public const FLAME = 16391;
    public const LAVA = 16392;
    public const LARGE_SMOKE = 16393;
    public const REDSTONE = 16394;
    public const RISING_RED_DUST = 16395;
    public const ITEM_BREAK = 16396;
    public const SNOWBALL_POOF = 16397;
    public const HUGE_EXPLODE = 16398;
    public const HUGE_EXPLODE_SEED = 16399;
    public const MOB_FLAME = 16400;
    public const HEART = 16401;
    public const TERRAIN = 16402;
    public const TOWN_AURA = 16403;
    public const PORTAL = 16404;
    public const WATER_SPLASH = 16405;
    public const WATER_WAKE = 16406;
    public const DRIP_WATER = 16407;
    public const DRIP_LAVA = 16408;
    public const FALLING_DUST = 16409;
    public const MOB_SPELL = 16410;
    public const MOB_SPELL_AMBIENT = 16411;
    public const MOB_SPELL_INSTANTANEOUS = 16412;
    public const INK = 16413;
    public const SLIME = 16414;
    public const RAIN_SPLASH = 16415;
    public const VILLAGER_ANGRY = 16416;
    public const VILLAGER_HAPPY = 16417;
    public const ENCHANTMENT_TABLE = 16418;
    public const TRACKING_EMITTER = 16419;
    public const NOTE = 16420;
    public const WITCH_SPELL = 16421;
    public const CARROT = 16422;
    public const END_ROD = 16424;
    public const DRAGON_BREATH = 16425;
    public const SHOOT = 2000;
    public const DESTROY = 2001;

    public $eventId;
    public $position;
    public $data;

    public function __constructor() {}

    public function __constructor($eventId, $position, $data)
    {
        $this->eventId = $eventId;
        $this->position = $position;
        $this->data = $data;
    }

}

