<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket111.xml
 */
namespace sul\protocol\play\pocket111;

use utils\Packet;

class StopSound extends Packet
{

    public const ID = 88;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $?;
    public $?;

    public function __constructor() {}

    public function __constructor($?, $?)
    {
        $this->? = $?;
        $this->? = $?;
    }

}

