<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket137.xml
 */
namespace sul\protocol\play\pocket137;

use utils\Packet;

class AvailableCommands extends Packet
{

    public const ID = 76;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $enumValues;
    public $unknown1;
    public $enums;
    public $commands;

    public function __constructor() {}

    public function __constructor($enumValues, $unknown1, $enums, $commands)
    {
        $this->enumValues = $enumValues;
        $this->unknown1 = $unknown1;
        $this->enums = $enums;
        $this->commands = $commands;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {




    }

    public function decode()
    {}

}

