<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/externalconsole1.xml
 */
namespace sul\protocol\connected\externalconsole1;

use utils\Packet;

class ConsoleMessage extends Packet
{

    public const ID = 4;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $node;
    public $timestamp;
    public $logger;
    public $message;

    public function __constructor() {}

    public function __constructor($node, $timestamp, $logger, $message)
    {
        $this->node = $node;
        $this->timestamp = $timestamp;
        $this->logger = $logger;
        $this->message = $message;
    }

}

