<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket110.xml
 */
namespace sul\protocol\play\pocket110;

use utils\Packet;

class GameRulesChanged extends Packet
{

    public const ID = 73;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $rules;

    public function __constructor() {}

    public function __constructor(\sul\protocol\pocket110\types\Rules $rules)
    {
        $this->rules = $rules;
    }

}

