<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket110.xml
 */
namespace sul\protocol\play\pocket110;

use utils\Packet;

class Login extends Packet
{

    public const ID = 1;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    // version
    public const VANILLA = 0;
    public const EDUCATION = 1;

    public $protocol = 110;
    public $version;
    public $bodyLength;
    public $body;

    public function __constructor() {}

    public function __constructor($protocol, $version, $bodyLength, \sul\protocol\pocket110\types\LoginBody $body)
    {
        $this->protocol = $protocol;
        $this->version = $version;
        $this->bodyLength = $bodyLength;
        $this->body = $body;
    }

}

