<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft109.xml
 */
namespace sul\protocol\clientbound\minecraft109;

use utils\Packet;

class VehicleMove extends Packet
{

    public const ID = 41;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $position;
    public $yaw;
    public $pitch;

    public function __constructor() {}

    public function __constructor($position, $yaw, $pitch)
    {
        $this->position = $position;
        $this->yaw = $yaw;
        $this->pitch = $pitch;
    }

}

