<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom1.xml
 */
namespace sul\protocol\login\hncom1;

use utils\Packet;

class ConnectionRequest extends Packet
{

    public const ID = 1;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $protocol;
    public $password;
    public $name;
    public $main = true;

    public function __constructor() {}

    public function __constructor($protocol, $password, $name, $main)
    {
        $this->protocol = $protocol;
        $this->password = $password;
        $this->name = $name;
        $this->main = $main;
    }

}

