<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom1.xml
 */
namespace sul\protocol\status\hncom1;

use utils\Packet;

class ResourcesUsage extends Packet
{

    public const ID = 10;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $tps;
    public $ram;
    public $cpu;

    public function __constructor() {}

    public function __constructor($tps, $ram, $cpu)
    {
        $this->tps = $tps;
        $this->ram = $ram;
        $this->cpu = $cpu;
    }

}

