<?php
/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul\utils;

use sul\utils\ItemData;

class Item {

	/** @var string */
	public $name;

	/** @var ItemData */
	public $minecraft, $pocket;

	/** @var int */
	public $stack;

	function __construct(string $name, ItemData $minecraft, ItemData $pocket, int $stack) {
		$this->name = $name;
		$this->minecraft = $minecraft;
		$this->pocket = $pocket;
		$this->stack = $stack;
	}

}