<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul\utils;

use sul\utils\ItemData;

class Item
{

    /** @var string */
    public $name;

    /** @var ItemData|null */
    public $java, $bedrock;

    /** @var int */
    public $stack;

    /**
     * @param string $name
     * @param ItemData|null $java
     * @param ItemData|null $bedrock
     * @param int $stack
     */
    public function __construct(string $name, $java, $bedrock, $stack)
    {
        $this->name = $name;
        $this->java = $java;
        $this->bedrock = $bedrock;
        $this->stack = $stack;
    }

}
