<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul\utils;

class ItemData
{

    /** @var int */
    public $id, $meta;

    /**
     * @param int $id
     * @param int $meta
     */
    public function __construct($id, $meta)
    {
        $this->id = $id;
        $this->meta = $meta;
    }

}
