<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/attributes/bedrock137.xml
 */
namespace sul\attributes;

class Bedrock
{

    const HEALTH = ["id" => "minecraft:health", "min" => 0, "max" => 20, "default" => 20];
    const ABSORPTION = ["id" => "minecraft:absorption", "min" => 0, "max" => 4, "default" => 0];
    const HUNGER = ["id" => "minecraft:player.hunger", "min" => 0, "max" => 20, "default" => 20];
    const SATURATION = ["id" => "minecraft:player.saturation", "min" => 0, "max" => 20, "default" => 5];
    const EXPERIENCE = ["id" => "minecraft:player.experience", "min" => 0, "max" => 1, "default" => 0];
    const LEVEL = ["id" => "minecraft:player.level", "min" => 0, "max" => 24791, "default" => 0];
    const SPEED = ["id" => "minecraft:movement", "min" => 0, "max" => 24791, "default" => 0.1];
    const KNOCKBACK_RESISTANCE = ["id" => "minecraft:generic.knockback_resistance", "min" => 0, "max" => 1, "default" => 0];

}
