<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/attributes/java340.xml
 */
namespace sul\attributes;

class Java
{

    const MAX_HEALTH = ["id" => "generic.maxHealth", "min" => 0, "max" => 1024, "default" => 20];
    const ABSORPTION = ["id" => "generic.absorption", "min" => 0, "max" => 4, "default" => 0];
    const MOVEMENT_SPEED = ["id" => "generic.movementSpeed", "min" => 0, "max" => 24791, "default" => 0.1];
    const KNOCKBACK_RESISTANCE = ["id" => "generic.knockbackResistance", "min" => 0, "max" => 1, "default" => 0];
    const ATTACK_DAMAGE = ["id" => "generic.attackDamage", "min" => 0, "max" => 2048, "default" => 2];
    const ATTACK_SPEED = ["id" => "generic.attackSpeed", "min" => 0, "max" => 1024, "default" => 4];

}
