<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/raknet8.xml
 */
namespace sul\protocol\encapsulated\raknet8;

use utils\Packet;

class Mcpe extends Packet
{

    public const ID = 254;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = true;

    public $packet;

    public function __constructor() {}

    public function __constructor($packet)
    {
        $this->packet = $packet;
    }

}

