/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
<?php

namespace sul\utils;

public class Attribute
{

    /** @var string */
    public $id;

    /** @var float */
    public $min, $max, $default;

    public function __construct(string $id, $min, $max, $default)
    {
        $this->id = $id;
        $this->min = $min;
        $this->max = $max;
        $this->default = $default;
    }

}
