/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
<?php

namespace sul\utils;

public class BlockData
{

    /** @var bool */
    public $exists;

    /** @var int */
    public $id, $meta;

}
