<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
namespace sul\utils;

use sul\utils\ItemData;

class Item
{

    /** @var string */
    public $name;

    /** @var ItemData|null */
    public $minecraft, $pocket;

    /** @var int */
    public $stack;

    /**
     * @param string $name
     * @param ItemData|null $minecraft
     * @param ItemData|null $pocket
     * @param int $stack
     */
    public function __construct(string $name, $minecraft, $pocket, $stack)
    {
        $this->name = $name;
        $this->minecraft = $minecraft;
        $this->pocket = $pocket;
        $this->stack = $stack;
    }

}
