/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
<?php

namespace sul\utils;

use sul\utils\ItemData;

public class Item
{

    /** @var string */
    public $name;

    /** @var int */
    public $index;

    /** @var ItemData */
    public $minecraft, $pocket;

    /** @var int */
    public $stack;

    public function __construct(string $name, int $index, ItemData $minecraft, ItemData $pocket, int $stack)
    {
        $this->name = $name;
        $this->index = $index;
        $this->minecraft = $minecraft;
        $this->pocket = $pocket;
        $this->stack = $stack;
    }

}
