<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft108.xml
 */
namespace sul\protocol\clientbound\minecraft108;

use utils\Packet;

class Effect extends Packet
{

    public const ID = 33;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    // effect id
    public const DISPENSER_DISPENSE = 1000;
    public const DISPENSER_FAIL_DISPENSE = 1001;
    public const DISPENSER_SHOOT = 1002;
    public const DOOR_OPEN_OR_CLOSE = 1003;
    public const FIREWORK_SHOT = 1004;
    public const PLAY_DISC = 1005;
    public const GHAST_WARN = 1007;
    public const GHAST_SHOOT = 1008;
    public const ZOMBIE_ATTACK_WOOD_DOOR = 1010;
    public const ZOMBIE_ATTACK_IRON_DOOR = 1011;
    public const ZOMBIE_BREAK_WOOD_DOOR = 1012;
    public const WITHER_SPAWN = 1013;
    public const WITHER_SHOOT = 1014;
    public const BAT_TAKE_OFF = 1015;
    public const ZOMBIE_INFECT_VILLAGER = 1016;
    public const ZOMBIE_VILLAGER_CONVERT = 1017;
    public const ANVIL_BREAK = 1019;
    public const ANVIL_USE = 1020;
    public const ANVIL_LAND = 1021;
    public const SPAWN_10_SMOKE_PARTICLES = 2000;
    public const BREAK_BREAK_PARTICLES = 2001;
    public const SPLASH_POTION_PARTICLES_AND_SOUND = 2002;
    public const ENDER_EYE_BREAK_PARTICLES_AND_SOUND = 2003;
    public const MOB_SPAWN_PARTICLES = 2004;
    public const BONEMEAL_PARTICLES = 2005;

    public $effectId;
    public $position;
    public $data;
    public $disableVolume;

    public function __constructor() {}

    public function __constructor($effectId, $position, $data, $disableVolume)
    {
        $this->effectId = $effectId;
        $this->position = $position;
        $this->data = $data;
        $this->disableVolume = $disableVolume;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {




    }

    public function decode()
    {}

}

