<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/externalconsole2.xml
 */
namespace sul\protocol\connected\externalconsole2;

use utils\Packet;

class Command extends Packet
{

    public const ID = 5;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $command;
    public $commandId;

    public function __constructor() {}

    public function __constructor($command, $commandId)
    {
        $this->command = $command;
        $this->commandId = $commandId;
    }

}

