<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft333.xml
 */
namespace sul\protocol\clientbound\minecraft333;

use utils\Packet;

class ResourcePackSend extends Packet
{

    public const ID = 51;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $url;
    public $hash;

    public function __constructor() {}

    public function __constructor($url, $hash)
    {
        $this->url = $url;
        $this->hash = $hash;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {


    }

    public function decode()
    {}

}

