<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket131.xml
 */
namespace sul\protocol\play\pocket131;

use utils\Packet;

class AdventureSettings extends Packet
{

    public const ID = 55;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = true;

    // flags
    public const IMMUTABLE_WORLD = 1;
    public const PVP_DISABLED = 2;
    public const PVM_DISABLED = 4;
    public const MVP_DISBALED = 8;
    public const EVP_DISABLED = 16;
    public const AUTO_JUMP = 32;
    public const ALLOW_FLIGHT = 64;
    public const NO_CLIP = 128;
    public const FLYING = 512;
    public const MUTED = 1024;

    // permissions
    public const BUILD_AND_MINE = 1;
    public const DOORS_AND_SWITCHES = 2;
    public const OPEN_CONTAINERS = 4;
    public const ATTACK_PLAYERS = 8;
    public const ATTACK_MOBS = 16;
    public const OP = 32;
    public const TELEPORT = 64;

    // permission level
    public const USER = 0;
    public const OPERATOR = 1;
    public const HOST = 2;
    public const AUTOMATION = 3;
    public const ADMIN = 4;

    public $flags;
    public $unknown1;
    public $permissions;
    public $permissionLevel;
    public $entityId;

    public function __constructor() {}

    public function __constructor($flags, $unknown1, $permissions, $permissionLevel, $entityId)
    {
        $this->flags = $flags;
        $this->unknown1 = $unknown1;
        $this->permissions = $permissions;
        $this->permissionLevel = $permissionLevel;
        $this->entityId = $entityId;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {





    }

    public function decode()
    {}

}

