<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
namespace sul\protocol\status\hncom2;

use utils\Packet;

class Reload extends Packet
{

    public const ID = 16;

    public const CLIENTBOUND = true;
    public const SERVERBOUND = false;

    public $displayName;
    public $motds;
    public $language;
    public $acceptedLanguages;
    public $socialJson;

    public function __constructor() {}

    public function __constructor($displayName, $motds, $language, $acceptedLanguages, $socialJson)
    {
        $this->displayName = $displayName;
        $this->motds = $motds;
        $this->language = $language;
        $this->acceptedLanguages = $acceptedLanguages;
        $this->socialJson = $socialJson;
    }

    public function getId()
    {
        return self::ID;
    }

    public function encode()
    {





    }

    public function decode()
    {}

}

