<?php

/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft110.xml
 */
namespace sul\protocol\serverbound\minecraft110;

use utils\Packet;

class ChatMessage extends Packet
{

    public const ID = 2;

    public const CLIENTBOUND = false;
    public const SERVERBOUND = true;

    public $text;

    public function __constructor() {}

    public function __constructor($text)
    {
        $this->text = $text;
    }

}

